//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_AgreementWithholdList
    {
        public int AgreementWithholdID { get; set; }
        public string AgreementWithholdName { get; set; }
        public Nullable<int> SettlementDebiID { get; set; }
        public string MethodOfSettling { get; set; }
        public string UseNo { get; set; }
        public string SettlementDebiList { get; set; }
    }
}
