//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_CheckRemerbenList
    {
        public int CheckRermeberID { get; set; }
        public string Remter { get; set; }
        public Nullable<System.DateTime> PablData { get; set; }
        public string CommodityType { get; set; }
        public string DrugType { get; set; }
        public Nullable<int> StockPlaceID { get; set; }
        public Nullable<int> OrderFormPactID { get; set; }
        public Nullable<int> GoodsClassifyID { get; set; }
        public Nullable<int> GoodsChopID { get; set; }
        public string ExamineName { get; set; }
        public Nullable<System.DateTime> ExamineTime { get; set; }
        public bool Entering { get; set; }
        public string EnteringTime { get; set; }
        public bool GoodsNot { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<decimal> YingKuiMoney { get; set; }
        public bool YuShenNot { get; set; }
        public bool ExamineNot { get; set; }
        public string ShenHeName { get; set; }
        public int DrugTypeID { get; set; }
        public bool YiJiaZaiGoodsNot { get; set; }
    }
}
