//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_GoodsClassifyList
    {
        public int GoodsClassifyID { get; set; }
        public string GoodsClassifyName { get; set; }
        public Nullable<int> F_GoodsClassifyID { get; set; }
        public string Code { get; set; }
        public string TurnoverData { get; set; }
        public Nullable<decimal> AdvanceCess { get; set; }
        public Nullable<decimal> PriceMarkupRate { get; set; }
        public Nullable<decimal> GrossProfitRate { get; set; }
        public Nullable<decimal> SellRate { get; set; }
        public Nullable<decimal> MemberDiscountRate { get; set; }
        public Nullable<decimal> ConsumeCess { get; set; }
    }
}
