//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_ManufacturerList
    {
        public int ManufacturerID { get; set; }
        public string ManufacturerName { get; set; }
        public string ManufacturerCode { get; set; }
        public string ManufacturerPC { get; set; }
        public string ManufacturerPYCode { get; set; }
        public string ManufacturerJCName { get; set; }
        public string ManufacturerProduct { get; set; }
        public string ManufacturerAddress { get; set; }
        public string ManufacturerBarCode { get; set; }
    }
}
