//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SupplierGoodsList
    {
        public int SupplierGoodsID { get; set; }
        public string SupplierGoodsName { get; set; }
        public Nullable<int> EstimateUnitID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> GoodsGenreID { get; set; }
        public Nullable<int> GoodsBrandID { get; set; }
        public string SpecificationsModel { get; set; }
        public Nullable<int> GoodsChopID { get; set; }
        public string ArtNo { get; set; }
    }
}
