//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_Unamelist
    {
        public int UnameID { get; set; }
        public string uname { get; set; }
        public string pwd { get; set; }
        public string phone { get; set; }
        public Nullable<bool> useof { get; set; }
        public Nullable<System.DateTime> EnrollTime { get; set; }
        public Nullable<decimal> MemberIntegral { get; set; }
        public string ShoppingNuber { get; set; }
    }
}
