//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_VoluntarilyOrderGoodsList
    {
        public int VoluntarilyOrderGoodsID { get; set; }
        public Nullable<int> GoodsDetailID { get; set; }
        public Nullable<int> OrderFormDetailID { get; set; }
        public string ZiDongDingDanHao { get; set; }
        public string Pack { get; set; }
        public Nullable<decimal> AdviseNumber { get; set; }
        public Nullable<decimal> AverageNumber { get; set; }
    }
}
