//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_AlternativeSupplierList
    {
        public int AlternativeSupplierID { get; set; }
        public string AlternativeSupplierName { get; set; }
        public string AlternativeSupplierTP { get; set; }
        public string AlternativeSupplierContacts { get; set; }
        public string AlternativeSupplierAddress { get; set; }
        public string AlternativeSupplierPC { get; set; }
        public Nullable<int> AlternativeID { get; set; }
    }
}
