//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CXSummaryList
    {
        public int CXSummaryID { get; set; }
        public string UXsable { get; set; }
        public string RXeturn { get; set; }
        public string TotalAmount { get; set; }
        public string GrandTotalAmount { get; set; }
        public string ToatalAgio { get; set; }
        public string GrandAgioAmount { get; set; }
        public string YuanKaHao { get; set; }
        public string XinKaHao { get; set; }
        public string Amount { get; set; }
        public string ZhaiYao { get; set; }
        public string HuiYuanXinMing { get; set; }
        public string JiLuBianHao { get; set; }
        public string YouXiaoQiKa { get; set; }
        public string ZuoFeiJinE { get; set; }
        public string ZuoFeiYuanYing { get; set; }
        public string ZuoFeiShuLiang { get; set; }
    }
}
