//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_MemberSCDList
    {
        public int MemberSCDID { get; set; }
        public string MemberSCDMC { get; set; }
        public string RecordNumber { get; set; }
        public string GSite { get; set; }
        public string FurlSite { get; set; }
        public string MemberType { get; set; }
    }
}
