//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_PackInfoIDList
    {
        public int PackInfoID { get; set; }
        public Nullable<int> GoodsDetailID { get; set; }
        public string PackContent { get; set; }
        public string PackWeight { get; set; }
        public bool DefaultPack { get; set; }
    }
}
