//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_StoreCardList
    {
        public int StoreCardID { get; set; }
        public Nullable<int> MembershipCardInfoID { get; set; }
        public Nullable<int> DeleteCardID { get; set; }
        public Nullable<int> TheCardsID { get; set; }
        public string StoreCardMC { get; set; }
        public string OrderNumber { get; set; }
        public string CardTypeCode { get; set; }
        public string Safekeeping { get; set; }
        public string Faceamount { get; set; }
        public string EctMoney { get; set; }
        public string Status { get; set; }
        public string Tab { get; set; }
        public string DeleteCause { get; set; }
    }
}
