//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_TheCardsList
    {
        public int TheCardsID { get; set; }
        public Nullable<int> SellingInfoID { get; set; }
        public string Kahao { get; set; }
        public string TheCardsMC { get; set; }
        public string TheCardsNumber { get; set; }
        public string CardPeriodOfValidity { get; set; }
        public string CardPersonalizationNumber { get; set; }
        public string CardPersonalizationStatus { get; set; }
        public string Ccustodian { get; set; }
        public string Recordnumber { get; set; }
    }
}
