//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_AgreementList
    {
        public int AgreementID { get; set; }
        public string AgreementName { get; set; }
        public string AgreementCode { get; set; }
        public Nullable<System.DateTime> AgreementBeginTime { get; set; }
        public Nullable<System.DateTime> AgreementFinishTime { get; set; }
        public Nullable<System.DateTime> ConclusionTime { get; set; }
        public Nullable<int> AdjustAccountsFashionID { get; set; }
        public Nullable<int> AgreementStateID { get; set; }
        public Nullable<int> GoodsID { get; set; }
    }
}
