//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_CheckRemerbenDetillList
    {
        public int CheckRemerbenDetillD { get; set; }
        public Nullable<int> CheckRermeberID { get; set; }
        public Nullable<int> GoodsID { get; set; }
        public Nullable<decimal> MumberOfPackages { get; set; }
        public Nullable<decimal> Subdivision { get; set; }
        public Nullable<decimal> PiCiHao { get; set; }
        public Nullable<decimal> SunYiShu { get; set; }
        public bool JiaZaiFou { get; set; }
        public Nullable<decimal> Attritionrate { get; set; }
    }
}
