//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_EffectiveList
    {
        public int EffectiveID { get; set; }
        public string EffectiveMC { get; set; }
        public string YEffective { get; set; }
        public string XEffective { get; set; }
        public string Sum { get; set; }
        public string EctMoney { get; set; }
        public string CardNber { get; set; }
        public string Name { get; set; }
        public string CredentialsNumber { get; set; }
        public string Status { get; set; }
    }
}
