//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_GoodsDetailList
    {
        public int GoodsDetailID { get; set; }
        public string GoodsDetailName { get; set; }
        public Nullable<int> GoodsID { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<decimal> RetailMonovalent { get; set; }
        public Nullable<decimal> GoodsFixAPrice { get; set; }
        public Nullable<decimal> ReferencePrice { get; set; }
        public Nullable<decimal> MemberPrice { get; set; }
        public Nullable<decimal> RateSale { get; set; }
        public Nullable<decimal> TaxBid { get; set; }
        public Nullable<decimal> NewRateSale { get; set; }
    }
}
