//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_GoodsChopList
    {
        public int GoodsChopID { get; set; }
        public string GoodsChopName { get; set; }
        public string SpellCod { get; set; }
        public string GoodsChopCode { get; set; }
        public Nullable<int> TrademarkRankID { get; set; }
        public Nullable<int> TrademarkStatusID { get; set; }
        public Nullable<int> TrademarkLocalID { get; set; }
        public string RegisteredAddress { get; set; }
        public Nullable<System.DateTime> DiplomaValid { get; set; }
        public string AgentCondition { get; set; }
        public string RegisteredDiploma { get; set; }
        public string Proprietor { get; set; }
    }
}
