//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_GoodsListedList
    {
        public int GoodsListedID { get; set; }
        public Nullable<int> ConverID { get; set; }
        public string ListedNumber { get; set; }
        public Nullable<int> SpouseBRanchID { get; set; }
        public string ConsigneeShop { get; set; }
        public string ConsigneeShopDiZhi { get; set; }
        public string payName { get; set; }
        public string furlName { get; set; }
        public string RegisterName { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public string ExamineName { get; set; }
        public Nullable<System.DateTime> ExamineTime { get; set; }
        public Nullable<int> GoodsDingYiQuID { get; set; }
        public bool ExamineNot { get; set; }
        public bool AbateNot { get; set; }
        public bool StoopSellNot { get; set; }
    }
}
