//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_GoodsList
    {
        public int GoodsID { get; set; }
        public string GoodsName { get; set; }
        public Nullable<int> GoodsStampID { get; set; }
        public Nullable<int> EstimateUnitID { get; set; }
        public Nullable<int> GoodsClassifyID { get; set; }
        public Nullable<int> GoodsSeasonID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> BurdenStockSellStatusID { get; set; }
        public string GoodsCode { get; set; }
        public Nullable<int> BarCodTypeID { get; set; }
        public string GoodsTiaoMa { get; set; }
        public string PLUCod { get; set; }
        public string SpellCod { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public string ProducingArea { get; set; }
        public string ArtNo { get; set; }
        public string SpecificationsModel { get; set; }
        public Nullable<int> ApplyTargetID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> GoodsChopID { get; set; }
        public Nullable<int> CommodityTypeID { get; set; }
        public Nullable<int> GoodsStatusID { get; set; }
        public string QualityGuaranteePeriod { get; set; }
        public string QualityContent { get; set; }
        public Nullable<decimal> StatisticsScale { get; set; }
        public Nullable<decimal> AdvanceCess { get; set; }
        public Nullable<decimal> SellCess { get; set; }
        public Nullable<int> GoodsColoursID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string Registrant { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> Checktime { get; set; }
        public Nullable<int> GoodsPurchasemoneyTypeID { get; set; }
        public Nullable<int> GoodsPurchasemoneyStatusID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> OrderFormPactID { get; set; }
        public Nullable<int> CountersellID { get; set; }
        public Nullable<int> PurchaseSectionID { get; set; }
        public bool AllowGoodsXiaoShu { get; set; }
        public bool AuditingBit { get; set; }
        public Nullable<int> ZhuanGuiCommodityTypeID { get; set; }
        public byte[] GoodsPicture { get; set; }
    }
}
