//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_GoodsBianJiaList
    {
        public int GoodsBianJiaID { get; set; }
        public Nullable<int> ChangeTypeID { get; set; }
        public string BianJiaBianHao { get; set; }
        public Nullable<int> GoodsDetailID { get; set; }
        public Nullable<decimal> NewMonovalent { get; set; }
        public Nullable<decimal> NewJob { get; set; }
        public Nullable<decimal> RawMemberValue { get; set; }
        public Nullable<int> ChangeWhyID { get; set; }
        public Nullable<System.DateTime> ChangeData { get; set; }
        public string Registrant { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> Checktime { get; set; }
        public string Executor { get; set; }
        public Nullable<System.DateTime> ExecuteTime { get; set; }
        public Nullable<int> SpouseBRanchID { get; set; }
        public Nullable<decimal> NewAdvanceBid { get; set; }
        public Nullable<decimal> NewNoAdvanceBid { get; set; }
        public Nullable<System.DateTime> BeginChangeData { get; set; }
        public Nullable<decimal> NewHanSuiJinHuoJia { get; set; }
        public Nullable<decimal> NewBuHanSuiJinHuoJia { get; set; }
        public Nullable<bool> GengXinCaiGouJiaFou { get; set; }
        public string Batch { get; set; }
    }
}
