//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_OrderFormPactList
    {
        public int OrderFormPactID { get; set; }
        public Nullable<int> AgreementTypeID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> AgreementStatusID { get; set; }
        public Nullable<int> SpouseBRanchID { get; set; }
        public string ContractNumber { get; set; }
        public string HandworkContractNumber { get; set; }
        public Nullable<int> AgreementManagerID { get; set; }
        public string HostContractNumber { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> MethodOfSettlingAccountsID { get; set; }
        public Nullable<System.DateTime> ValidTip { get; set; }
        public Nullable<System.DateTime> ValidBegin { get; set; }
        public Nullable<System.DateTime> ConclusionTime { get; set; }
        public string ConclusionSite { get; set; }
        public string PurchasingAgent { get; set; }
        public Nullable<System.DateTime> AdvanceMarketData { get; set; }
        public Nullable<System.DateTime> RetreatMarketData { get; set; }
        public Nullable<System.DateTime> WritData { get; set; }
        public Nullable<System.DateTime> AccountData { get; set; }
        public Nullable<System.DateTime> AdvancedSettleAccounts { get; set; }
        public Nullable<System.DateTime> PlanFiringData { get; set; }
        public Nullable<System.DateTime> Firingdata { get; set; }
        public Nullable<int> AgreementID { get; set; }
        public Nullable<int> AdjustAccountsFashionID { get; set; }
        public Nullable<int> GoodsID { get; set; }
        public Nullable<int> TryPaymentData { get; set; }
        public Nullable<int> TryPaymentShiXiaoData { get; set; }
        public string AgreementRen { get; set; }
        public string Registrant { get; set; }
        public string Auditor { get; set; }
        public string Executor { get; set; }
        public Nullable<System.DateTime> Registranttime { get; set; }
        public Nullable<System.DateTime> Auditortime { get; set; }
        public Nullable<System.DateTime> Executortime { get; set; }
        public Nullable<bool> UseOf { get; set; }
        public Nullable<int> GoodsGenreID { get; set; }
        public Nullable<int> GoodsChopID { get; set; }
    }
}
