//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_PurchaseList
    {
        public int PurchaseID { get; set; }
        public Nullable<int> GoodsDetailID { get; set; }
        public string PurchasingAgent { get; set; }
        public string PricePlace { get; set; }
        public string PricePlace2 { get; set; }
        public string PricePlace3 { get; set; }
        public string PricePlace4 { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<decimal> Price4 { get; set; }
        public Nullable<System.DateTime> PriceData { get; set; }
        public Nullable<decimal> NoAdvanceBid { get; set; }
        public Nullable<decimal> AdvanceBid { get; set; }
        public Nullable<decimal> PurchasePriceMarkup { get; set; }
        public Nullable<decimal> LastBid { get; set; }
    }
}
