//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SellDeTaLsit
    {
        public int SellDeTaliID { get; set; }
        public Nullable<int> SellID { get; set; }
        public Nullable<int> ConverDeTaiID { get; set; }
        public Nullable<int> ConverID { get; set; }
    }
}
