//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SellCheckBatchList
    {
        public int SellCheckBatchID { get; set; }
        public Nullable<int> SellID { get; set; }
        public string Remember { get; set; }
        public Nullable<int> MaiChangID { get; set; }
        public Nullable<int> SpouseBRanchID { get; set; }
        public Nullable<int> DrugTypeID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public Nullable<int> StaffIDTwo { get; set; }
        public Nullable<System.DateTime> ExamineTime { get; set; }
        public bool ExamineNot { get; set; }
    }
}
