//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_ShoppingList
    {
        public int ShoppingID { get; set; }
        public Nullable<int> UnameID { get; set; }
        public Nullable<int> GoodsListedDetailID { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string BitColer { get; set; }
        public Nullable<decimal> MumberOfPackages { get; set; }
        public bool SubmitNot { get; set; }
        public bool AffirmNot { get; set; }
    }
}
