//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_StaffList
    {
        public int StaffID { get; set; }
        public string StaffName { get; set; }
        public string StaffCode { get; set; }
        public Nullable<int> StaffClassID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UniformAuthenticationCode { get; set; }
    }
}
