//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_SupplierList
    {
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierNumber { get; set; }
        public string SupplierCHName { get; set; }
        public string SupplierAbbreviation { get; set; }
        public string SupplierEnglishName { get; set; }
        public string SupplierPTCode { get; set; }
        public string SupplierDependency { get; set; }
        public string SupplierRegisteredAddress { get; set; }
        public Nullable<int> UnitCharacterID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string SupplierRegisteredEnglish { get; set; }
        public Nullable<int> SupplierRankID { get; set; }
        public Nullable<int> AgreementTypeID { get; set; }
        public Nullable<int> AgreementStateID { get; set; }
        public string Registrant { get; set; }
        public string Auditor { get; set; }
        public string Executor { get; set; }
        public Nullable<System.DateTime> Registranttime { get; set; }
        public Nullable<System.DateTime> Auditortime { get; set; }
        public Nullable<System.DateTime> Executortime { get; set; }
        public string SupplierInformationName { get; set; }
        public string SupplierTelephone { get; set; }
        public string SupplierContacts { get; set; }
        public string SupplierPost { get; set; }
        public string SupplierEmail { get; set; }
        public string SupplierZipCode { get; set; }
        public string SupplierPortraiture { get; set; }
        public string SupplierAddress { get; set; }
        public string SupplierURL { get; set; }
        public Nullable<int> EnterpriseNatureID { get; set; }
        public Nullable<int> EnterpriseTypeID { get; set; }
        public string EnterpriseBank { get; set; }
        public string EnterpriseNumber { get; set; }
        public string NationalTaxNumber { get; set; }
        public string LocalTaxNumber { get; set; }
        public string EnterprisePassword { get; set; }
    }
}
