//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_WareHouseDetiailList
    {
        public int WareHouseDetiailID { get; set; }
        public Nullable<int> WareHouseID { get; set; }
        public Nullable<int> OrderFormDetailID { get; set; }
        public Nullable<decimal> MumberOfPackages { get; set; }
        public Nullable<decimal> Subdivision { get; set; }
        public bool YiKongNot { get; set; }
        public Nullable<decimal> YuanMumberOfPack { get; set; }
        public Nullable<decimal> YuanSubdivision { get; set; }
    }
}
