//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DaXingShangMaoXiTongEntities : DbContext
    {
        public DaXingShangMaoXiTongEntities()
            : base("name=DaXingShangMaoXiTongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<areas> areas { get; set; }
        public virtual DbSet<B_AgreementList> B_AgreementList { get; set; }
        public virtual DbSet<B_AgreementWithholdList> B_AgreementWithholdList { get; set; }
        public virtual DbSet<B_AllocateDetailList> B_AllocateDetailList { get; set; }
        public virtual DbSet<B_AllocateList> B_AllocateList { get; set; }
        public virtual DbSet<B_ApproachCostList> B_ApproachCostList { get; set; }
        public virtual DbSet<B_ChangeDetailList> B_ChangeDetailList { get; set; }
        public virtual DbSet<B_ChangeList> B_ChangeList { get; set; }
        public virtual DbSet<B_CheckRemerbenDetillList> B_CheckRemerbenDetillList { get; set; }
        public virtual DbSet<B_CheckRemerbenList> B_CheckRemerbenList { get; set; }
        public virtual DbSet<B_ChGoodsPanlSexList> B_ChGoodsPanlSexList { get; set; }
        public virtual DbSet<B_ConverDeTailList> B_ConverDeTailList { get; set; }
        public virtual DbSet<B_ConverList> B_ConverList { get; set; }
        public virtual DbSet<B_CustomerCardList> B_CustomerCardList { get; set; }
        public virtual DbSet<B_DaBaoDingJiaList> B_DaBaoDingJiaList { get; set; }
        public virtual DbSet<B_DefaulGoodsDetaiLList> B_DefaulGoodsDetaiLList { get; set; }
        public virtual DbSet<B_DefaulGoodsList> B_DefaulGoodsList { get; set; }
        public virtual DbSet<B_DefaultrelevDetaiLList> B_DefaultrelevDetaiLList { get; set; }
        public virtual DbSet<B_DefaultrelevList> B_DefaultrelevList { get; set; }
        public virtual DbSet<B_DeleteCardList> B_DeleteCardList { get; set; }
        public virtual DbSet<B_DepatmenList> B_DepatmenList { get; set; }
        public virtual DbSet<B_EffectiveList> B_EffectiveList { get; set; }
        public virtual DbSet<B_GoodsBianJiaList> B_GoodsBianJiaList { get; set; }
        public virtual DbSet<B_GoodsChopList> B_GoodsChopList { get; set; }
        public virtual DbSet<B_GoodsClassifyList> B_GoodsClassifyList { get; set; }
        public virtual DbSet<B_GoodsDetailList> B_GoodsDetailList { get; set; }
        public virtual DbSet<B_GoodsKuCunList> B_GoodsKuCunList { get; set; }
        public virtual DbSet<B_GoodsList> B_GoodsList { get; set; }
        public virtual DbSet<B_GoodsListedDetailList> B_GoodsListedDetailList { get; set; }
        public virtual DbSet<B_GoodsListedList> B_GoodsListedList { get; set; }
        public virtual DbSet<B_GoodsSignList> B_GoodsSignList { get; set; }
        public virtual DbSet<B_IncreaseDetailList> B_IncreaseDetailList { get; set; }
        public virtual DbSet<B_IncreaseList> B_IncreaseList { get; set; }
        public virtual DbSet<B_InvalidList> B_InvalidList { get; set; }
        public virtual DbSet<B_ManufacturerList> B_ManufacturerList { get; set; }
        public virtual DbSet<B_NewGoodsManageList> B_NewGoodsManageList { get; set; }
        public virtual DbSet<B_OrderFormDetailList> B_OrderFormDetailList { get; set; }
        public virtual DbSet<B_OrderFormList> B_OrderFormList { get; set; }
        public virtual DbSet<B_OrderFormPactDetailList> B_OrderFormPactDetailList { get; set; }
        public virtual DbSet<B_OrderFormPactList> B_OrderFormPactList { get; set; }
        public virtual DbSet<B_PackGoodsList> B_PackGoodsList { get; set; }
        public virtual DbSet<B_PanlList> B_PanlList { get; set; }
        public virtual DbSet<B_PurchaseList> B_PurchaseList { get; set; }
        public virtual DbSet<B_RetureFactoryDeTailList> B_RetureFactoryDeTailList { get; set; }
        public virtual DbSet<B_RetureFactoryList> B_RetureFactoryList { get; set; }
        public virtual DbSet<B_SaleAdjustList> B_SaleAdjustList { get; set; }
        public virtual DbSet<B_SellCheckBatchDetaiList> B_SellCheckBatchDetaiList { get; set; }
        public virtual DbSet<B_SellCheckBatchList> B_SellCheckBatchList { get; set; }
        public virtual DbSet<B_SellDeTaLsit> B_SellDeTaLsit { get; set; }
        public virtual DbSet<B_SellList> B_SellList { get; set; }
        public virtual DbSet<B_SellRetuerDateiList> B_SellRetuerDateiList { get; set; }
        public virtual DbSet<B_SellRetuerList> B_SellRetuerList { get; set; }
        public virtual DbSet<B_ShooppingDateilIDOrderFounList> B_ShooppingDateilIDOrderFounList { get; set; }
        public virtual DbSet<B_ShooppingOrderFountList> B_ShooppingOrderFountList { get; set; }
        public virtual DbSet<B_ShooppingSellList> B_ShooppingSellList { get; set; }
        public virtual DbSet<B_ShoppingList> B_ShoppingList { get; set; }
        public virtual DbSet<B_SourceList> B_SourceList { get; set; }
        public virtual DbSet<B_StaffList> B_StaffList { get; set; }
        public virtual DbSet<B_StaffRoleDetailList> B_StaffRoleDetailList { get; set; }
        public virtual DbSet<B_StockList> B_StockList { get; set; }
        public virtual DbSet<B_SupplierGoodsList> B_SupplierGoodsList { get; set; }
        public virtual DbSet<B_SupplierList> B_SupplierList { get; set; }
        public virtual DbSet<B_TakeGlanceList> B_TakeGlanceList { get; set; }
        public virtual DbSet<B_ThreeSingleList> B_ThreeSingleList { get; set; }
        public virtual DbSet<B_Unamelist> B_Unamelist { get; set; }
        public virtual DbSet<B_VoluntarilyOrderGoodsList> B_VoluntarilyOrderGoodsList { get; set; }
        public virtual DbSet<B_WanManifestDetailList> B_WanManifestDetailList { get; set; }
        public virtual DbSet<B_WanManifestList> B_WanManifestList { get; set; }
        public virtual DbSet<B_WareHouseDetiailList> B_WareHouseDetiailList { get; set; }
        public virtual DbSet<B_WareHouseList> B_WareHouseList { get; set; }
        public virtual DbSet<B_WeatherList> B_WeatherList { get; set; }
        public virtual DbSet<B_WithholdContrastList> B_WithholdContrastList { get; set; }
        public virtual DbSet<S_AdjustAccountsFashionList> S_AdjustAccountsFashionList { get; set; }
        public virtual DbSet<S_AdjustTypeList> S_AdjustTypeList { get; set; }
        public virtual DbSet<S_AgioTimeIntervalList> S_AgioTimeIntervalList { get; set; }
        public virtual DbSet<S_AgioTimeIntervalTypeList> S_AgioTimeIntervalTypeList { get; set; }
        public virtual DbSet<S_AgreementManagerList> S_AgreementManagerList { get; set; }
        public virtual DbSet<S_AgreementStateList> S_AgreementStateList { get; set; }
        public virtual DbSet<S_AgreementTypeList> S_AgreementTypeList { get; set; }
        public virtual DbSet<S_AlternativeList> S_AlternativeList { get; set; }
        public virtual DbSet<S_AlternativeProjectList> S_AlternativeProjectList { get; set; }
        public virtual DbSet<S_AlternativeSupplierList> S_AlternativeSupplierList { get; set; }
        public virtual DbSet<S_ApplyTargetList> S_ApplyTargetList { get; set; }
        public virtual DbSet<S_AreaCodeList> S_AreaCodeList { get; set; }
        public virtual DbSet<S_BarCodTypeList> S_BarCodTypeList { get; set; }
        public virtual DbSet<S_BurdenStockSellStatusList> S_BurdenStockSellStatusList { get; set; }
        public virtual DbSet<S_CardValiditySpecifiedList> S_CardValiditySpecifiedList { get; set; }
        public virtual DbSet<S_ChangeTypeList> S_ChangeTypeList { get; set; }
        public virtual DbSet<S_ChangeWhyList> S_ChangeWhyList { get; set; }
        public virtual DbSet<S_CommodityTypeList> S_CommodityTypeList { get; set; }
        public virtual DbSet<S_CompanyList> S_CompanyList { get; set; }
        public virtual DbSet<S_ContactCertificate> S_ContactCertificate { get; set; }
        public virtual DbSet<S_CounterList> S_CounterList { get; set; }
        public virtual DbSet<S_CXSummaryList> S_CXSummaryList { get; set; }
        public virtual DbSet<S_EnterpriseNatureList> S_EnterpriseNatureList { get; set; }
        public virtual DbSet<S_EnterpriseTypeList> S_EnterpriseTypeList { get; set; }
        public virtual DbSet<S_EstimateUnitList> S_EstimateUnitList { get; set; }
        public virtual DbSet<S_GoodsBottomPriceList> S_GoodsBottomPriceList { get; set; }
        public virtual DbSet<S_GoodsBrandList> S_GoodsBrandList { get; set; }
        public virtual DbSet<S_GoodsGenreIDList> S_GoodsGenreIDList { get; set; }
        public virtual DbSet<S_GoodsMoneyRuleList> S_GoodsMoneyRuleList { get; set; }
        public virtual DbSet<S_GoodsPurchasemoneyStatusList> S_GoodsPurchasemoneyStatusList { get; set; }
        public virtual DbSet<S_GoodsPurchasemoneyTypeList> S_GoodsPurchasemoneyTypeList { get; set; }
        public virtual DbSet<S_GoodsSeasonList> S_GoodsSeasonList { get; set; }
        public virtual DbSet<S_GoodsStampList> S_GoodsStampList { get; set; }
        public virtual DbSet<S_GoodsStatusIList> S_GoodsStatusIList { get; set; }
        public virtual DbSet<S_GoodsTypeSpecificationList> S_GoodsTypeSpecificationList { get; set; }
        public virtual DbSet<S_HuoDongZhuanQu> S_HuoDongZhuanQu { get; set; }
        public virtual DbSet<S_MaiChangList> S_MaiChangList { get; set; }
        public virtual DbSet<S_MakeCollectionsList> S_MakeCollectionsList { get; set; }
        public virtual DbSet<S_MarketNameList> S_MarketNameList { get; set; }
        public virtual DbSet<S_MemberCredentialsType> S_MemberCredentialsType { get; set; }
        public virtual DbSet<S_MemberFamilyMember> S_MemberFamilyMember { get; set; }
        public virtual DbSet<S_MemberHobbiesInterests> S_MemberHobbiesInterests { get; set; }
        public virtual DbSet<S_MemberInfoList> S_MemberInfoList { get; set; }
        public virtual DbSet<S_MemberMemberEd> S_MemberMemberEd { get; set; }
        public virtual DbSet<S_MemberMemberFamilyIncome> S_MemberMemberFamilyIncome { get; set; }
        public virtual DbSet<S_MemberProfession> S_MemberProfession { get; set; }
        public virtual DbSet<S_MemberSCDList> S_MemberSCDList { get; set; }
        public virtual DbSet<S_MembershipAgeList> S_MembershipAgeList { get; set; }
        public virtual DbSet<S_MembershipCardAccount> S_MembershipCardAccount { get; set; }
        public virtual DbSet<S_MembershipCardForm> S_MembershipCardForm { get; set; }
        public virtual DbSet<S_MembershipCardInfoList> S_MembershipCardInfoList { get; set; }
        public virtual DbSet<S_MembershipCardList> S_MembershipCardList { get; set; }
        public virtual DbSet<S_MembershipCardSafekeeping> S_MembershipCardSafekeeping { get; set; }
        public virtual DbSet<S_MembershipCardStatusList> S_MembershipCardStatusList { get; set; }
        public virtual DbSet<S_MembershipCardSupervise> S_MembershipCardSupervise { get; set; }
        public virtual DbSet<S_MembershipCardTypeList> S_MembershipCardTypeList { get; set; }
        public virtual DbSet<S_MemberTimeToMall> S_MemberTimeToMall { get; set; }
        public virtual DbSet<S_MemberVehicle> S_MemberVehicle { get; set; }
        public virtual DbSet<S_MethodOfSettlingAccountsList> S_MethodOfSettlingAccountsList { get; set; }
        public virtual DbSet<S_ModuleList> S_ModuleList { get; set; }
        public virtual DbSet<S_OrderFormTypeList> S_OrderFormTypeList { get; set; }
        public virtual DbSet<S_PackInfoIDList> S_PackInfoIDList { get; set; }
        public virtual DbSet<S_PaymentList> S_PaymentList { get; set; }
        public virtual DbSet<S_PersonalIformationList> S_PersonalIformationList { get; set; }
        public virtual DbSet<S_PreferentialFashionList> S_PreferentialFashionList { get; set; }
        public virtual DbSet<S_PriceTypeList> S_PriceTypeList { get; set; }
        public virtual DbSet<S_PublishWayList> S_PublishWayList { get; set; }
        public virtual DbSet<S_QuFenLeiXingList> S_QuFenLeiXingList { get; set; }
        public virtual DbSet<S_ReturnofList> S_ReturnofList { get; set; }
        public virtual DbSet<S_SellAssemblelist> S_SellAssemblelist { get; set; }
        public virtual DbSet<S_SellingInfoList> S_SellingInfoList { get; set; }
        public virtual DbSet<S_SettlementDebiList> S_SettlementDebiList { get; set; }
        public virtual DbSet<S_SignTypeList> S_SignTypeList { get; set; }
        public virtual DbSet<S_SpouseBRanchList> S_SpouseBRanchList { get; set; }
        public virtual DbSet<S_StaffClassList> S_StaffClassList { get; set; }
        public virtual DbSet<S_StaffPowerList> S_StaffPowerList { get; set; }
        public virtual DbSet<S_StatisticAttribute> S_StatisticAttribute { get; set; }
        public virtual DbSet<S_StockPlaceList> S_StockPlaceList { get; set; }
        public virtual DbSet<S_StoreCardList> S_StoreCardList { get; set; }
        public virtual DbSet<S_SupplierGroupList> S_SupplierGroupList { get; set; }
        public virtual DbSet<S_SupplierRankList> S_SupplierRankList { get; set; }
        public virtual DbSet<S_SupplierReturnTypeList> S_SupplierReturnTypeList { get; set; }
        public virtual DbSet<S_TheCardsbranchList> S_TheCardsbranchList { get; set; }
        public virtual DbSet<S_TheCardsList> S_TheCardsList { get; set; }
        public virtual DbSet<S_TrademarkLocalList> S_TrademarkLocalList { get; set; }
        public virtual DbSet<S_TrademarkRankList> S_TrademarkRankList { get; set; }
        public virtual DbSet<S_TrademarkStatusList> S_TrademarkStatusList { get; set; }
        public virtual DbSet<S_UnitCharacterList> S_UnitCharacterList { get; set; }
        public virtual DbSet<S_VieOpponentList> S_VieOpponentList { get; set; }
        public virtual DbSet<S_WithholdTypeList> S_WithholdTypeList { get; set; }
        public virtual DbSet<S_ZhuanGuiCommodityTypeLiat> S_ZhuanGuiCommodityTypeLiat { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<S_GoodsColoursList> S_GoodsColoursList { get; set; }
    }
}
