//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_GoodsSeasonList
    {
        public int GoodsSeasonID { get; set; }
        public string GoodsSeasonName { get; set; }
        public string KaiShiYue { get; set; }
        public string KaiShiRi { get; set; }
        public string JieShuYue { get; set; }
        public string jieShuRi { get; set; }
    }
}
