//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_MemberInfoList
    {
        public int AreaID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string XingMing { get; set; }
        public string Sex { get; set; }
        public string CredentialsNumber { get; set; }
        public string PostalAddress { get; set; }
        public string Location { get; set; }
        public string Postalcode { get; set; }
        public string dianziyoujian { get; set; }
        public string Profession { get; set; }
        public string OfficePhone { get; set; }
        public string PrivateTelephone { get; set; }
        public string CellphoneNumber { get; set; }
        public string CardNumberChange { get; set; }
        public string Amount { get; set; }
        public string UntreatedIntegral { get; set; }
        public string CredentialsType { get; set; }
        public string MemberFamilyIncome { get; set; }
        public string MemberEd { get; set; }
        public string TimeToMall { get; set; }
        public string Vehicle { get; set; }
        public string FamilyMember { get; set; }
        public string HobbiesInterests { get; set; }
        public string CustomQuality { get; set; }
        public string BirthDate { get; set; }
        public string CommentsOnAForm { get; set; }
    }
}
