//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_MembershipCardInfoList
    {
        public int MembershipCardInfoID { get; set; }
        public string CardNber { get; set; }
        public string Sum { get; set; }
        public string EctMoney { get; set; }
        public string Ccustodian { get; set; }
        public string CardNumber { get; set; }
        public string StartCardNbumer { get; set; }
        public string EndCardNber { get; set; }
        public string StoreNumb { get; set; }
        public string Cost { get; set; }
        public string Interior { get; set; }
        public string SurelySite { get; set; }
        public string CardCode { get; set; }
        public string CredentialsNumber { get; set; }
        public string GrandTotalAmount { get; set; }
        public string TheCardsDate { get; set; }
    }
}
