//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_PersonalIformationList
    {
        public int PersonalIformationID { get; set; }
        public Nullable<int> UnameID { get; set; }
        public string Location { get; set; }
        public string Detailedaddress { get; set; }
        public string Zipcode { get; set; }
        public string Consignee { get; set; }
        public string Phone { get; set; }
        public string Phonecode { get; set; }
        public byte[] UserImage { get; set; }
        public bool MoRenDiZhiBit { get; set; }
    }
}
