//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_SellingInfoList
    {
        public int SellingInfoID { get; set; }
        public Nullable<int> MembershipCardAccountID { get; set; }
        public Nullable<int> CouponUID { get; set; }
        public Nullable<int> MakeCollectionsID { get; set; }
        public Nullable<int> PublishWaysID { get; set; }
        public Nullable<int> PreferentialFashionID { get; set; }
        public Nullable<int> CXSummaryID { get; set; }
        public string MInspectionCard { get; set; }
        public string Gtotal { get; set; }
        public string SingleFee { get; set; }
        public string RAmount { get; set; }
        public string XAmount { get; set; }
        public string FeeAmount { get; set; }
        public string Summary { get; set; }
    }
}
