//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXingShangMaoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_TheCardsbranchList
    {
        public int TheCardsbranchID { get; set; }
        public Nullable<int> SellingInfoID { get; set; }
        public Nullable<int> TheCardsID { get; set; }
        public string TheCardsbranchMC { get; set; }
        public string CodeRule { get; set; }
        public string Store { get; set; }
        public string Code { get; set; }
    }
}
